apiVersion: v1
kind: Service
metadata:
  name: sctp-lb1
  annotations:
    loxilb.io/num-secondary-networks: "2"
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "fullnat"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: sctp-test
  ports:
    - port: 55002
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-test
  labels:
    what: sctp-test
spec:
  containers:
    - name: sctp-test
      image: loxilb-io/sctp-server:latest
      imagePullPolicy: Never
      #command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
      ports:
        - containerPort: 9999
