apiVersion: v1
kind: Service
metadata:
  name: tcp-lb-oa-ss
  labels:
    app: tcp-lb-oa-ss
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "onearm"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: tcp-lb-oa-ss
  ports:
  - port: 58002
    targetPort: 80
    name: tcp-ss
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tcp-ss
spec:
  selector:
    matchLabels:
      app: tcp-lb-oa-ss
  serviceName: "tcp-lb-oa-ss"
  replicas: 2
  template:
    metadata:
      labels:
        app: tcp-lb-oa-ss
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tcp-lb-oa-ss
        image: ghcr.io/loxilb-io/nginx:stable
        ports:
        - containerPort: 80
          name: tcp-ss
