name: Adv-LB-Sanity-CI-Ubuntu-24

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Advanced LB Sanity ubuntu 24'
       
jobs:
  build:
    name: advanced-lb-sanity-ubuntu-24
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v3
        with:
             go-version: '>=1.18.0'
      - run: |
             cd cicd/k8slbsim/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/onearml2/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/ulcltcplb/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/ulclsctplb/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/tcptunlb/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/sctptunlb/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/wrrtcplb1/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/wrrtcplb2/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/nat64tcp/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
