name: Sanity-CI-Ubuntu-24
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'Sanity-BuildCI-u24'
  workflow_run:
    workflows: ["Build-CI"]
    types:
      - completed
jobs:
  build:
    name: basic-sanity-ubuntu-24
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v3
        with:
             go-version: '>=1.18.0'
      - run: |
             cd cicd/sconnect/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/tcplb/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
