name: Build-Check-CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      userInput:
        description: 'Enter string to print at end'
        required: true
        default: 'Finished'
      tags:
        description: 'Build Check'  

jobs:

  build:
    name: build-check-ci

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Latest Docker
      run: |
        sudo apt-get purge runc 
        echo 'Done remove runc'
        sudo apt-get remove docker docker-engine docker.io containerd | true
        sudo apt-get purge docker-ce docker-ce-cli containerd.io | true
        sudo rm -rf /etc/bash_completion.d/docker /usr/local/bin/docker-compose /etc/bash_completion.d/docker-compose | true
        sudo apt install containerd -y | true
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update
        sudo apt-get install docker-ce

    - name: Build the loxilb Docker image
      run: |
        docker build . --tag ghcr.io/loxilb-io/loxilb:latest
        docker run -u root --cap-add SYS_ADMIN  --restart unless-stopped --privileged -dit -v /dev/log:/dev/log --name loxilb ghcr.io/loxilb-io/loxilb:latest
    - run: echo ${{ github.event.inputs.userInput }}
