name: Build-Check-CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      userInput:
        description: 'Enter string to print at end'
        required: true
        default: 'Finished'
      tags:
        description: 'Build Check'  

jobs:

  build:
    name: build-check-ci

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: sudo apt-get update
    - run: sudo apt -y install clang llvm libelf-dev gcc-multilib libpcap-dev linux-tools-$(uname -r) elfutils dwarves git libbsd-dev bridge-utils unzip build-essential bison flex iproute2
    - run: BPFTOOL=`which bpftool`
    - run: echo $(BPFTOOL)

    - name: Build the loxilb Docker image
      run: |
        docker build . --tag ghcr.io/loxilb-io/loxilb:latest
        docker run -u root --cap-add SYS_ADMIN  --restart unless-stopped --privileged -dit -v /dev/log:/dev/log --name loxilb ghcr.io/loxilb-io/loxilb:latest
    - run: echo ${{ github.event.inputs.userInput }}
