name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the loxilb Docker image
      run: |
          docker build -t loxilb-io/loxilb .
          docker push ghcr.io/loxilb-io/loxilb:latest
