name:  Docker-Multi-Arch
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    name: build for amd64/arm64
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    # Setup hardware emulator using QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    # Setup Docker Buildx for multi-arch images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Check
      if: |
          github.repository != 'loxilb-io/loxilb'
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: false
        tags: ghcr.io/loxilb-io/loxilb:latest
          
    - name: Build and push
      if: |
          github.repository == 'loxilb-io/loxilb'
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ghcr.io/loxilb-io/loxilb:latest
