name: K3s-Flannel-InCluster-Sanity-CI
on:
 schedule:
 # Runs "At 17:00 UTC every day-of-week"
 - cron: '0 17 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k3s-flannel-incluster'
jobs:
  build:
    name: k3s-flannel-incluster-sanity
    runs-on: self-hosted
    if: github.repository == 'TrekkieCoder/loxilb' 
          &&  github.event.inputs.tagName == ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run the test
        run: |
         cd cicd/k3s-flannel-incluster
         ./config.sh
         sleep 120
         ./validation.sh
         vagrant ssh host -c "socat -T10 - sctp:123.123.123.1:55004,bind=192.168.90.9"
         vagrant ssh host -c "socat -T10 - sctp:123.123.123.1:57004,bind=192.168.90.9"
         cd -
         
      - name: Clean test-bed
        if: success() || failure()
        run: |
          cd cicd/k3s-flannel-incluster || true
          #./rmconfig.sh
          cd -
