name: K3s-Flannel-Sanity-CI
on:
 schedule:
 # Runs "At 11:00 UTC every day-of-week"
 - cron: '0 11 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k3s-flannel'
jobs:
  build:
    name: k3s-flannel-sanity
    runs-on: self-hosted
    steps:
      - if: github.repository == 'TrekkieCoder/loxilb'
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
         echo "KUBECONFIG=--kubeconfig=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV
         echo "ubuntu=20.04" >> $GITHUB_ENV
         cd cicd/k3s-flannel/
         ./config.sh "${{ env.KUBECONFIG }}" "${{ env.ubuntu }}"
         ./validation.sh "${{ env.KUBECONFIG }}"
         ./rmconfig.sh "${{ env.KUBECONFIG }}"
         cd -
