name: K8s-Validation-CI
on:
 #schedule:
 # Runs "At 13:00 UTC every day-of-week"
 #- cron: '0 13 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k8s-calico'
jobs:
  build:
    name: k8s-calico-cluster-sanity
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
         cd $ {{ github.event.inputs.testName }}
         ./validation.sh
         cd -
