name: SCTP-LB-Sanity-CI-Ubuntu-24

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'SCTP LB Sanity Ubuntu 24'
       
jobs:
  build:
    name: sctp-lb-sanity-ubuntu-24
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v3
        with:
             go-version: '>=1.18.0'
      - run: sudo apt-get update
      - run: sudo apt-get -y install linux-tools-$(uname -r) iperf iproute2 nodejs socat ethtool lksctp-tools
      - run: |
             cd cicd/sctplb/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/sctponearm/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/sctplbdsr/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/sctplblc/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
